---
- name: Install AutoSSH package
  yum: name=autossh state=installed

- name: Install daemon config for autossh
  template: src=autossh-template.service dest=/etc/systemd/system/{{ autossh_daemon_name }}
  notify: systemctl daemon-reload

- name: Start and enable on startup the autossh daemon
  service: name={{ autossh_daemon_name }} state=running enabled=yes


